You’re the sunlight, the rivers and rain
The midnight chills rolling over the plain
A butterfly rising, breaks free
all the colours in the world  visible to me

I feel alive when you touch my skin
When you pull closer and let me in

You are.... the air that i breathe 
you make me believe each heartbeat rises 
you're the rhythm in me.
You are.... the air that i breathe 

You’re the warm breeze that settles my mind
The steady calm I never thought I’d find
A quiet strength that carries me through
Every part of the world feels clearer with you

I feel the rush when you hold me near
Your touch makes me lose my fears

You are.... the air that i breathe 
you make me believe each heartbeat rises 
you're the rhythm in me.
You are.... the air that i breathe 

come a little bit closer and whisper like you do
come a little closer bb we have a minute or 2
